# This file contains non-secret configurations.

# API webserver configuration.
webserver:
  port: 8871
  endpoint: "/v1"
  subscriptions: "/ws"

# Prisma configuration.
prisma:
  endpoint: "http://localhost:4466/houston"
  secret: ~
  debug: false

# Database connection.
# This is mostly for knexfile now.
# Also defined for Prisma service separately.
database:
  # Knex migrations
  migrations:
    tableName: migrations
    schemaName: houston$default

  # Knex connection
  connection:
    user: postgres
    password: postgres
    host: localhost
    port: 5432
    database: postgres

# Commander configuration.
commander:
  enabled: false
  host: localhost
  port: 50051

# Charts live here.
# This is where the airflow chart is installed from.
repository: "https://helm.astronomer.io/"

# Helm configuration.
# These values are set at runtime and used for airflow deployments.
helm:
  baseDomain: ~
  registryAuthSecret: ~
  releaseName: ~
  releaseNamespace: ~
  releaseVersion: ~
  singleNamespace: false

# Auth configuration.
auth:
  # Local database (user/pass) configuration.
  local:
    enabled: true

  # Auth0 integration configuration.
  auth0:
    enabled: false
    clientId: ~
    baseDomain: ~
    externalLogin: ~

  # Direct oauth integration to google.
  google:
    enabled: false
    clientId: ~

# Passphrase to sign JWTs with.
jwtPassphrase: ~

# JWT / Cookie duration in milliseconds.
authDuration: 86400000

# Allow public signups.
publicSignups: false

# Require email confirmation.
emailConfirmation: true

# Format: ${SCOPE}.${RESOURCE}.${VERB}
roles:
  #
  # System
  #
  - id: SYSTEM_ADMIN
    name: System Admin
    permissions:
      - global.systemSettings.create
      - global.systemSettings.get
      - global.systemSettings.list
      - global.systemSettings.update
      - global.systemSettings.delete
      - global.workspace.get
      - global.workspace.list
      - global.workspace.update
      - global.workspace.delete
      - global.deployment.get
      - global.deployment.list
      - global.deployment.update
      - global.deployment.delete

  - id: SYSTEM_EDITOR
    name: System Editor
    permissions:
      - global.systemSettings.get
      - global.systemSettings.list
      - global.systemSettings.update

  - id: SYSTEM_VIEWER
    name: System Viewer
    permissions:
      - global.systemSettings.get
      - global.systemSettings.list

  #
  # Workspace
  #
  - id: WORKSPACE_ADMIN
    name: Workspace Admin
    permissions:
      - user.workspace.get
      - user.workspace.update
      - user.workspace.delete
      - user.deployment.create
      - user.deployment.list

  - id: WORKSPACE_EDITOR
    name: Workspace Editor
    permissions:
      - user.workspace.get
      - user.workspace.update
      - user.deployment.create
      - user.deployment.list

  - id: WORKSPACE_VIEWER
    name: Workspace Viewer
    permissions:
      - user.workspace.get
      - user.deployment.list

  #
  # Deployment
  #
  - id: DEPLOYMENT_ADMIN
    name: Deployment Admin
    permissions:
      - user.deployment.get
      - user.deployment.update
      - user.deployment.delete

  - id: DEPLOYMENT_EDITOR
    name: Deployment Editor
    permissions:
      - user.deployment.get
      - user.deployment.update

  - id: DEPLOYMENT_VIEWER
    name: Deployment Viewer
    permissions:
      - user.deployment.get

#
# Airflow Deployment Configurations
#
deployments:
  # This is the database connection that we use to connect
  # and create other databases/schemas/users for each
  # individual airflow deployment.
  database:
    # If disabled, skip db creation.
    enabled: true

    # Keep the airflow databases around after a
    # deployment is deleted.
    retainOnDelete: false

    # If true, leave GRANTs in place for root user.
    # This lets users log in with the root creds and query
    # deployment databases.
    allowRootAccess: false

    # Connection details for root user.
    connection:
      user: postgres
      password: postgres
      host: localhost
      port: 5432
      database: postgres

  # An astro unit defines the smallest billable unit
  # in the system. Default values are based on
  # the GCP n1-standard-1. CPU should always be expressed
  # in millicpu and memory should be expressed in Mibibytes.
  astroUnit:
    cpu: 100
    memory: 384
    pods: 1
    airflowConns: 5
    actualConns: 0.5
    # price: 10

  # This defines how much extra capacity, in astro units,
  # that a user can expand a deployment to. This is currently
  # represented as a slider in the UI.
  maxExtraAu: 400

  # This defines the maximum size a pod can be in astro units.
  maxPodAu: 35

  # This defines all possible components for an airflow
  # deployment and the default AU to use for the kubernetes 
  # resource requests, as well as its limits.
  components:
    - name: scheduler
      au:
        default: 5
        limit: 30
    - name: webserver
      au:
        default: 2
        limit: 30
    - name: statsd
      au:
        default: 2
        limit: 30
    - name: pgbouncer
      au:
        default: 2
        limit: 2
    - name: flower
      au:
        default: 2
        limit: 2
    - name: redis
      au:
        default: 2
        limit: 2
    - name: workers
      au:
        default: 10
        limit: 30
      extra:
        - name: terminationGracePeriodSeconds
          default: 600
          limit: 36000
        - name: replicas
          default: 1
          limit: 10

  # This defines which executors should be supported, as well
  # as the components required to run a particular
  # executor configuration.
  executors:
    - name: LocalExecutor
      enabled: true
      components:
        - scheduler
        - webserver
        - statsd
        - pgbouncer
    - name: CeleryExecutor
      enabled: true
      components:
        - scheduler
        - webserver
        - statsd
        - pgbouncer
        - workers
        - flower
        - redis
    - name: KubernetesExecutor
      enabled: false
      components:
        - scheduler
        - webserver
        - statsd
        - pgbouncer

  # These are static configs that get merged directly into the values
  # passed to helm for each deployment.
  helm:
    rbacEnabled: true
    ingress:
      enabled: true
      acme: false
    networkPolicies:
      enabled: true
    pgbouncer:
      enabled: true
